default: &default
  adapter: mysql2
  encoding: utf8
  pool: 68
  timeout: 5000
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: dc_face

test: &test
  <<: *default
  database: dc_face

production:
  <<: *default
  database: dc_face
